//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmtconfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cmtconfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Lifetime.
        /// </summary>
        internal static string ABOUT_FORM_LICENSE {
            get {
                return ResourceManager.GetString("ABOUT_FORM_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string ATTRIBUTES_FORM_FUNCTION {
            get {
                return ResourceManager.GetString("ATTRIBUTES_FORM_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string ATTRIBUTES_FORM_LINE {
            get {
                return ResourceManager.GetString("ATTRIBUTES_FORM_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string ATTRIBUTES_FORM_MACRO {
            get {
                return ResourceManager.GetString("ATTRIBUTES_FORM_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application exiting....
        /// </summary>
        internal static string AUTOUPDATER_APP_CLOSING {
            get {
                return ResourceManager.GetString("AUTOUPDATER_APP_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem reaching update server. Please check your internet connection and try again later..
        /// </summary>
        internal static string AUTOUPDATER_FAILED_CONNECTION {
            get {
                return ResourceManager.GetString("AUTOUPDATER_FAILED_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new version {0} available. You are using version {1}. This is required update. Press Ok to begin updating the application..
        /// </summary>
        internal static string AUTOUPDATER_NEW_MANDATORY_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("AUTOUPDATER_NEW_MANDATORY_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new version {0} available. You are using version {1}. Do you want to update the application now?.
        /// </summary>
        internal static string AUTOUPDATER_NEW_VERSION_AVAILABLE {
            get {
                return ResourceManager.GetString("AUTOUPDATER_NEW_VERSION_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no update available. Please try again later..
        /// </summary>
        internal static string AUTOUPDATER_NO_UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("AUTOUPDATER_NO_UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing file .
        /// </summary>
        internal static string EDITOR_FORM_ANALYSING_FILE {
            get {
                return ResourceManager.GetString("EDITOR_FORM_ANALYSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis rotating....
        /// </summary>
        internal static string EDITOR_FORM_AXIS_ROTATING {
            get {
                return ResourceManager.GetString("EDITOR_FORM_AXIS_ROTATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        internal static string EDITOR_FORM_CONVERTING {
            get {
                return ResourceManager.GetString("EDITOR_FORM_CONVERTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering deleting....
        /// </summary>
        internal static string EDITOR_FORM_DELETING_NUMBERING {
            get {
                return ResourceManager.GetString("EDITOR_FORM_DELETING_NUMBERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loading in progress, please wait....
        /// </summary>
        internal static string EDITOR_FORM_FILE_LOADING {
            get {
                return ResourceManager.GetString("EDITOR_FORM_FILE_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting....
        /// </summary>
        internal static string EDITOR_FORM_FORMATTING {
            get {
                return ResourceManager.GetString("EDITOR_FORM_FORMATTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string EDITOR_FORM_HELP {
            get {
                return ResourceManager.GetString("EDITOR_FORM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is modified. Save file?.
        /// </summary>
        internal static string EDITOR_FORM_MODIFIED_FILE {
            get {
                return ResourceManager.GetString("EDITOR_FORM_MODIFIED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string EDITOR_FORM_NEW_FILE {
            get {
                return ResourceManager.GetString("EDITOR_FORM_NEW_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumbering.....
        /// </summary>
        internal static string EDITOR_FORM_RENUMBERING {
            get {
                return ResourceManager.GetString("EDITOR_FORM_RENUMBERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts the code snippet:\n.
        /// </summary>
        internal static string EDITOR_FORM_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("EDITOR_FORM_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist: .
        /// </summary>
        internal static string ERROR_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("ERROR_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ERROR_FORM_COLUMN {
            get {
                return ResourceManager.GetString("ERROR_FORM_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ERROR_FORM_DESCRIPTION {
            get {
                return ResourceManager.GetString("ERROR_FORM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string ERROR_FORM_LINE {
            get {
                return ResourceManager.GetString("ERROR_FORM_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Tool / Control not set!.
        /// </summary>
        internal static string ERROR_MACHINE_NOT_SET {
            get {
                return ResourceManager.GetString("ERROR_MACHINE_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks Number.
        /// </summary>
        internal static string FILE_SPLITTER_FORM_BLOCK_NUMBER {
            get {
                return ResourceManager.GetString("FILE_SPLITTER_FORM_BLOCK_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string FILE_SPLITTER_FORM_TEXT {
            get {
                return ResourceManager.GetString("FILE_SPLITTER_FORM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Call.
        /// </summary>
        internal static string FILE_SPLITTER_FORM_TOOL_CALL {
            get {
                return ResourceManager.GetString("FILE_SPLITTER_FORM_TOOL_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Work Path.
        /// </summary>
        internal static string FILE_SPLITTER_FORM_TOOL_WORK_PATH {
            get {
                return ResourceManager.GetString("FILE_SPLITTER_FORM_TOOL_WORK_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Work Time.
        /// </summary>
        internal static string FILE_SPLITTER_FORM_TOOL_WORK_TIME {
            get {
                return ResourceManager.GetString("FILE_SPLITTER_FORM_TOOL_WORK_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file containing errors can not be split..
        /// </summary>
        internal static string FILE_SPLITTING_FILE_WITH_ERRORS {
            get {
                return ResourceManager.GetString("FILE_SPLITTING_FILE_WITH_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current file will be split into .
        /// </summary>
        internal static string FILE_SPLITTING_MANY_FILES {
            get {
                return ResourceManager.GetString("FILE_SPLITTING_MANY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  files. Continue?.
        /// </summary>
        internal static string FILE_SPLITTING_MANY_FILES_CONTINUE {
            get {
                return ResourceManager.GetString("FILE_SPLITTING_MANY_FILES_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to split..
        /// </summary>
        internal static string FILE_SPLITTING_NOTHING_TO_SPLIT {
            get {
                return ResourceManager.GetString("FILE_SPLITTING_NOTHING_TO_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the file. Search completed..
        /// </summary>
        internal static string FIND_FORM_FILE_END {
            get {
                return ResourceManager.GetString("FIND_FORM_FILE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line range (1 - {0}):.
        /// </summary>
        internal static string GOTO_FORM_LINE_RANGE {
            get {
                return ResourceManager.GetString("GOTO_FORM_LINE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absolute.
        /// </summary>
        internal static string INFO_FORM_ABSOLUTE {
            get {
                return ResourceManager.GetString("INFO_FORM_ABSOLUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        internal static string INFO_FORM_AXIS {
            get {
                return ResourceManager.GetString("INFO_FORM_AXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolant.
        /// </summary>
        internal static string INFO_FORM_COOLANT {
            get {
                return ResourceManager.GetString("INFO_FORM_COOLANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutter Comp..
        /// </summary>
        internal static string INFO_FORM_CUTTER_COMPENSATION {
            get {
                return ResourceManager.GetString("INFO_FORM_CUTTER_COMPENSATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedrate.
        /// </summary>
        internal static string INFO_FORM_FEEDRATE {
            get {
                return ResourceManager.GetString("INFO_FORM_FEEDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        internal static string INFO_FORM_INCH {
            get {
                return ResourceManager.GetString("INFO_FORM_INCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incremental.
        /// </summary>
        internal static string INFO_FORM_INCREMENTAL {
            get {
                return ResourceManager.GetString("INFO_FORM_INCREMENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position relative to the Machine range.
        /// </summary>
        internal static string INFO_FORM_MACHINE_RELATIVE_POS {
            get {
                return ResourceManager.GetString("INFO_FORM_MACHINE_RELATIVE_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string INFO_FORM_MAX {
            get {
                return ResourceManager.GetString("INFO_FORM_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string INFO_FORM_MIN {
            get {
                return ResourceManager.GetString("INFO_FORM_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millimeter.
        /// </summary>
        internal static string INFO_FORM_MM {
            get {
                return ResourceManager.GetString("INFO_FORM_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Total.
        /// </summary>
        internal static string INFO_FORM_PATH_TOTAL {
            get {
                return ResourceManager.GetString("INFO_FORM_PATH_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position relative to Program Zero.
        /// </summary>
        internal static string INFO_FORM_PROGRAM_ZERO_RELATIVE_POS {
            get {
                return ResourceManager.GetString("INFO_FORM_PROGRAM_ZERO_RELATIVE_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        internal static string INFO_FORM_PROGRAMMING {
            get {
                return ResourceManager.GetString("INFO_FORM_PROGRAMMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle.
        /// </summary>
        internal static string INFO_FORM_SPINDLE {
            get {
                return ResourceManager.GetString("INFO_FORM_SPINDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Total.
        /// </summary>
        internal static string INFO_FORM_TIME_TOTAL {
            get {
                return ResourceManager.GetString("INFO_FORM_TIME_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Number.
        /// </summary>
        internal static string INFO_FORM_TOOL_ID {
            get {
                return ResourceManager.GetString("INFO_FORM_TOOL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Path.
        /// </summary>
        internal static string INFO_FORM_TOOL_PATH {
            get {
                return ResourceManager.GetString("INFO_FORM_TOOL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Time.
        /// </summary>
        internal static string INFO_FORM_TOOL_TIME {
            get {
                return ResourceManager.GetString("INFO_FORM_TOOL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string INFO_FORM_UNITS {
            get {
                return ResourceManager.GetString("INFO_FORM_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string INFO_FORM_VALUE {
            get {
                return ResourceManager.GetString("INFO_FORM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string LIBRARY_FORM_VIEW {
            get {
                return ResourceManager.GetString("LIBRARY_FORM_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View / Edit.
        /// </summary>
        internal static string LIBRARY_FORM_VIEW_EDIT {
            get {
                return ResourceManager.GetString("LIBRARY_FORM_VIEW_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string MACRO_VAR_FORM_LINE {
            get {
                return ResourceManager.GetString("MACRO_VAR_FORM_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string MACRO_VAR_FORM_PARAM {
            get {
                return ResourceManager.GetString("MACRO_VAR_FORM_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Product Code....
        /// </summary>
        internal static string MAINFORM_ACTIVATE {
            get {
                return ResourceManager.GetString("MAINFORM_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic analysis.
        /// </summary>
        internal static string MAINFORM_ANALYSIS_AUTOMATIC {
            get {
                return ResourceManager.GetString("MAINFORM_ANALYSIS_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis disabled.
        /// </summary>
        internal static string MAINFORM_ANALYSIS_DISABLED {
            get {
                return ResourceManager.GetString("MAINFORM_ANALYSIS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Product Code.
        /// </summary>
        internal static string MAINFORM_DEACTIVATE {
            get {
                return ResourceManager.GetString("MAINFORM_DEACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC Program Correct.
        /// </summary>
        internal static string MAINFORM_PROGRAM_CORRECT {
            get {
                return ResourceManager.GetString("MAINFORM_PROGRAM_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC Program Incorrect.
        /// </summary>
        internal static string MAINFORM_PROGRAM_INCORRECT {
            get {
                return ResourceManager.GetString("MAINFORM_PROGRAM_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC Program Unchecked.
        /// </summary>
        internal static string MAINFORM_PROGRAM_UNCHECKED {
            get {
                return ResourceManager.GetString("MAINFORM_PROGRAM_UNCHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Opened Files....
        /// </summary>
        internal static string MAINFORM_RECENTLY_OPENED_FILES {
            get {
                return ResourceManager.GetString("MAINFORM_RECENTLY_OPENED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_CODE {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code {0} already exists in group {1}.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_CODE_EXISTS_IN_GROUP {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_CODE_EXISTS_IN_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - copy.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_COPY {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_DEFAULT {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_DESCRIPTION {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group already exists.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_GROUP_EXISTS {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_GROUP_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_GROUP_NAME {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_NO_NAME {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active profile.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_NO_PROFILE {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_NO_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile already exists.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_PROFILE_EXISTS {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_PROFILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string MCODES_EDITOR_FORM_PROFILE_NAME {
            get {
                return ResourceManager.GetString("MCODES_EDITOR_FORM_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon nceditor {
            get {
                object obj = ResourceManager.GetObject("nceditor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not available in the Lite version.
        /// </summary>
        internal static string NOT_AVAILABLE_IN_LITE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE_IN_LITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line #.
        /// </summary>
        internal static string PATH_FORM_LINE_NUMBER {
            get {
                return ResourceManager.GetString("PATH_FORM_LINE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Positioning Path.
        /// </summary>
        internal static string PATH_FORM_RAPID_POSITIONING_PATH {
            get {
                return ResourceManager.GetString("PATH_FORM_RAPID_POSITIONING_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Positioning Time.
        /// </summary>
        internal static string PATH_FORM_RAPID_POSITIONING_TIME {
            get {
                return ResourceManager.GetString("PATH_FORM_RAPID_POSITIONING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool #.
        /// </summary>
        internal static string PATH_FORM_TOOL_NUMBER {
            get {
                return ResourceManager.GetString("PATH_FORM_TOOL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Path.
        /// </summary>
        internal static string PATH_FORM_TOOL_PATH {
            get {
                return ResourceManager.GetString("PATH_FORM_TOOL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Time.
        /// </summary>
        internal static string PATH_FORM_TOOL_TIME {
            get {
                return ResourceManager.GetString("PATH_FORM_TOOL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Path.
        /// </summary>
        internal static string PATH_FORM_TOTAL_PATH {
            get {
                return ResourceManager.GetString("PATH_FORM_TOTAL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string PATH_FORM_TOTAL_TIME {
            get {
                return ResourceManager.GetString("PATH_FORM_TOTAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Path.
        /// </summary>
        internal static string PATH_FORM_WORKING_PATH {
            get {
                return ResourceManager.GetString("PATH_FORM_WORKING_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time.
        /// </summary>
        internal static string PATH_FORM_WORKING_TIME {
            get {
                return ResourceManager.GetString("PATH_FORM_WORKING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change requires application restart to take effect.
        /// </summary>
        internal static string PROGRAM_SETTINGS_FORM_RESTART {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_FORM_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of File..
        /// </summary>
        internal static string REPLACE_FORM_FILE_END {
            get {
                return ResourceManager.GetString("REPLACE_FORM_FILE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced {0} occurrence(s)..
        /// </summary>
        internal static string REPLACE_FORM_REPLACED {
            get {
                return ResourceManager.GetString("REPLACE_FORM_REPLACED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rotation.
        /// </summary>
        internal static string ROTATE_AXES_FORM_NO_ROTATION {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_NO_ROTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis, 180 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_X180 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_X180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis, 270 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_X270 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_X270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis, 90 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_X90 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_X90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis, 180 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_Y180 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_Y180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis, 270 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_Y270 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_Y270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis, 90 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_Y90 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_Y90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z axis, 180 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_Z180 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_Z180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z axis, 270 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_Z270 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_Z270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z axis, 90 degrees.
        /// </summary>
        internal static string ROTATE_AXES_FORM_Z90 {
            get {
                return ResourceManager.GetString("ROTATE_AXES_FORM_Z90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application settings....
        /// </summary>
        internal static string SPLASHSCREEN_APPLICATION_SETTINGS {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_APPLICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the current NC settings....
        /// </summary>
        internal static string SPLASHSCREEN_CURRENT_NC_SETTINGS {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_CURRENT_NC_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading default NC settings....
        /// </summary>
        internal static string SPLASHSCREEN_DEFAULT_NC_SETTINGS {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_DEFAULT_NC_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating dockable windows....
        /// </summary>
        internal static string SPLASHSCREEN_DOCKABLE_WINDOWS {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_DOCKABLE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the availability of a new version of the program....
        /// </summary>
        internal static string SPLASHSCREEN_NEW_VERSION {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading a list of recently opened files....
        /// </summary>
        internal static string SPLASHSCREEN_RECENT_FILES {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_RECENT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying the program license....
        /// </summary>
        internal static string SPLASHSCREEN_VERIFYING_LICENSE {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_VERIFYING_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading window settings....
        /// </summary>
        internal static string SPLASHSCREEN_WINDOW_SETTINGS {
            get {
                return ResourceManager.GetString("SPLASHSCREEN_WINDOW_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the product code to continue using the application..
        /// </summary>
        internal static string TA_ACTIVATE_CONTINUE_USING {
            get {
                return ResourceManager.GetString("TA_ACTIVATE_CONTINUE_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to deactivation failed: .
        /// </summary>
        internal static string TA_FAILED_DEACTIVATION {
            get {
                return ResourceManager.GetString("TA_FAILED_DEACTIVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check the remaining days until the end of the trial version: .
        /// </summary>
        internal static string TA_FAILED_TRIAL_END_CHECK {
            get {
                return ResourceManager.GetString("TA_FAILED_TRIAL_END_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run the trial version: .
        /// </summary>
        internal static string TA_FAILED_TRIAL_RUN {
            get {
                return ResourceManager.GetString("TA_FAILED_TRIAL_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check the validity of the activation: .
        /// </summary>
        internal static string TA_FAILED_VALIDITY_ACTIVATION_CHECK {
            get {
                return ResourceManager.GetString("TA_FAILED_VALIDITY_ACTIVATION_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - The trial has expired.
        /// </summary>
        internal static string TA_TRIAL_EXPIRED {
            get {
                return ResourceManager.GetString("TA_TRIAL_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Your trial expires in .
        /// </summary>
        internal static string TA_TRIAL_EXPIRES {
            get {
                return ResourceManager.GetString("TA_TRIAL_EXPIRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days.
        /// </summary>
        internal static string TA_TRIAL_EXPIRES_DAYS {
            get {
                return ResourceManager.GetString("TA_TRIAL_EXPIRES_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. More details in:\r\n.
        /// </summary>
        internal static string UNKNOWN_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR_MESSAGE", resourceCulture);
            }
        }
    }
}
